### ISSUE TITLE
Config function does not affect Test button

### ISSUE THREAD

**Issue by msholly** [bugsnag/bugsnag-wordpress#43]
### Expected behavior
I added the `$bugsnagWordpress->setReleaseStage('development');` to the theme file, per documentation. The "Test Bugsnag" button that triggers a test event should be affected by this configuration. 

### Observed behavior
The Test button always reports Production, which was mostly just confusing why records continued to show as Prod. A real error must be triggered for Development to appear in BugSnag dashboard. 

### Steps to reproduce
Configure BugSnag's setReleaseStage method, and go to BugSnag settings in the Wordpress Admin and trigger a test event.

### Version
1.4.0

Thanks Bugsnag team!

**Comment by xander-jones** [comment]
Hi @msholly, thanks for letting us know about this. It's defaulting to `production` as the call is made asynchronously where `WP_ENV` is not defined, which sets the `releaseStage` in turn.

On lines https://github.com/bugsnag/bugsnag-wordpress/blob/edd51174d4b159e4928d29a637d1ef4c9bbc0544/bugsnag.php#L268-L279 you can see it's using the `$_POST` data to send this test, rather than the configuration in your theme.

The test button is designed to check that your API key is correct and that you have installed the plugin correctly. However, I think it may be worth updating our documentation or code to clear this up. I will pass this on to our team.

**Comment by msholly** [comment]
Thanks for the clarification! Yes, it was mostly just confusing and I wanted to give a new user perspective on the initial onboarding process. Since in this case, I was actually testing my config, rather than the API connection.

**Comment by johnkiely1** [comment]
This has been fixed in version [V1.5.0](https://github.com/bugsnag/bugsnag-wordpress/releases/tag/v1.5.0)
